export interface Transaction {
    id: string;
    date: Date;
    amount: number;
    description: string;
    category: string;
    payee: string;
    type: 'expense' | 'income';
    source?: string; // CSV, PDF, Manual
    isRecurring?: boolean;
    tags?: string[];
}

export interface Budget {
    id: string;
    category: string;
    amount: number;
    period: 'monthly' | 'weekly' | 'yearly';
    rollover: boolean;
    isPersonalized: boolean; // Generated by AI
    historicalAverage?: number;
    seasonalityFactor?: number;
}

export interface Goal {
    id: string;
    name: string;
    targetAmount: number;
    currentAmount: number;
    deadline: Date;
    priority: 'high' | 'medium' | 'low';
    category: string;
}

export interface Forecast {
    date: Date;
    projectedBalance: number;
    confidence: number; // 0-1
    factors: string[];
}

export interface Subscription {
    id: string;
    name: string;
    amount: number;
    frequency: 'monthly' | 'yearly' | 'weekly';
    lastUsed?: Date;
    isZombie: boolean; // Used < 1 time in 3 months
    cancelUrl?: string;
}

export interface PhantomSpend {
    category: string;
    frequency: number; // transactions per month
    averageAmount: number;
    totalMonthly: number;
    annualizedCost: number;
    examples: Transaction[];
}

export interface BurnRate {
    percentage: number; // (Expenses - Debt) / Income
    status: 'healthy' | 'warning' | 'critical';
    monthlyExpenses: number;
    monthlyIncome: number;
    debtPayments: number;
}

export interface SavingsVelocity {
    percentage: number; // Month-over-month % change
    trend: 'increasing' | 'decreasing' | 'stable';
    netWorthChange: number;
}

export interface ProcurementRecommendation {
    itemName: string;
    identifiedPrice: number;
    marketPrice: number;
    budgetCategory: string;
    budgetRemaining: number;
    recommendation: 'buy' | 'wait' | 'avoid';
    reasoning: string;
    alternatives?: Array<{
        name: string;
        price: number;
        savings: number;
    }>;
    tco?: number; // Total Cost of Ownership
}

export interface Challenge {
    id: string;
    name: string;
    type: 'no-spend' | 'budget-underrun' | 'savings-streak';
    startDate: Date;
    endDate: Date;
    target: number;
    progress: number;
    status: 'active' | 'completed' | 'failed';
    reward?: string;
}

export interface Alert {
    id: string;
    type: 'overdraft' | 'budget-exceeded' | 'price-drop' | 'cooling-off' | 'subscription';
    severity: 'info' | 'warning' | 'critical';
    message: string;
    actionable: boolean;
    action?: string;
    createdAt: Date;
}

export interface UserPreferences {
    apiKeys: {
        deepseek?: string;
        groq?: string;
        gemini?: string;
        googleSearch?: string;
    };
    coolingOffRules: Array<{
        category: string;
        threshold: number;
        delayMinutes: number;
    }>;
    notificationsEnabled: boolean;
    currency: string;
    locale: string;
}
